---
kind: ConfigMap
apiVersion: v1

metadata:
  name: sos-ep-config
data:
  application.json:
    ' {
    "mil.dia.merlin.mockmessage.kafka.bootstrap-server": "kafka-0.kafka-headless.merlin-phase1.svc.cluster.local:9092",
    "server.port": 8080
  }'
---
kind: Deployment
apiVersion: apps/v1

metadata:
  name: sos-endpoint
  labels:
    name: sos-endpoint
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sos-endpoint
  template:
    metadata:
      labels:
        name: sos-endpoint
    spec:
      initContainers:
        - name: sos-enpoint-initializer
          image: registry.localdev.me/sos-endpoint-initializer:latest
          env:
            - name: SPRING_APPLICATION_JSON
              valueFrom:
                configMapKeyRef:
                  name: sos-ep-config
                  key: application.json
      containers:
        - name: sos-endpoint
          image: registry.localdev.me/sos-endpoint-controller:latest
          env:
            - name: SPRING_APPLICATION_JSON
              valueFrom:
                configMapKeyRef:
                  name: sos-ep-config
                  key: application.json
          ports:
            - containerPort: 8080
              name: sos-ep-port
---
apiVersion: v1
kind: Service
metadata:
  name: sos-ep-svc
  labels:
    run: sos-ep-svc
spec:
  type: NodePort
  selector:
    name: sos-endpoint
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: sos-endpoint-ingress
spec:
  rules:
    - host: merlin.localdev.me
      http:
        paths:
          - backend:
              service:
                name: sos-ep-svc
                port:
                  number: 8080
            path: /sos
            pathType: Prefix

